USE BolBcp

--##################	ESTADISTICAS TARJETAS DE CREDITOS	--##################
--PASO 1 SEPARA LOS VALORES POR TIPO CLASIFICACION
DROP TABLE IF EXISTS ##TEMP1
SELECT CAST(FECHA AS DATE) AS FECHA_CIERRE
	  ,tc.CODIGO_ENTIDAD
	  ,e.Entidad
	  --,CLASIFICACIÓN
	  ,CASE WHEN CLASIFICACIÓN='Cantidad' THEN TOTAL ELSE 0 END AS CantTC
	  ,CASE WHEN CLASIFICACIÓN='Saldo' THEN TOTAL ELSE 0 END AS SaldoTC
	  ,TOTAL
	  ,FECHA_CARGA
  INTO ##TEMP1	-- SELECT * FROM ##TEMP1
  FROM dbo.TC JOIN dbo.DeParabanco e ON tc.codigo_entidad=e.Codigo_Entidad

 -- PASO 2 AGRUPAR POR TOTALES DE TIPO CLASIFICACION EN UNA SOLA LINEA POR FECHA CIERRE Y ENTIDAD
SELECT FECHA_CIERRE
	  --,CODIGO_ENTIDAD
	  ,Entidad
	  --,CLASIFICACIÓN
	  ,SUM(CantTC) AS CantTC
	  ,SUM(SaldoTC) AS SaldoTC
	  ,SUM(TOTAL) AS TOTAL
	  ,'TC' AS sheet
  FROM ##TEMP1
 GROUP BY FECHA_CIERRE,Entidad
--###########################################################################

DROP TABLE IF EXISTS ##TEMP_Cartera
SELECT CAST(FECHA AS DATE) AS FECHA_CIERRE
	  ,C.CODIGO_ENTIDAD
	  ,E.ENTIDAD
	  ,CODIGO_CUENTA
	  ,CASE WHEN CODIGO_MONEDA=6900 THEN IMPORTE ELSE 0 END AS Saldo_MN
	  ,CASE WHEN CODIGO_MONEDA=6200 THEN IMPORTE ELSE 0 END AS Saldo_ML
	  ,IMPORTE
	  ,FECHA_CARGA
  INTO ##TEMP_Cartera	-- SELECT * FROM ##TEMP_Cartera
  FROM dbo.Carteras c JOIN dbo.DeParabanco e ON c.codigo_entidad=e.Codigo_Entidad

   -- PASO 2 AGRUPAR POR TOTALES DE TIPO CLASIFICACION EN UNA SOLA LINEA POR FECHA CIERRE Y ENTIDAD

   SELECT FECHA_CIERRE
		 ,ENTIDAD
		 ,codigo_cuenta
		 ,SUM(Saldo_MN) AS Saldo_MN
		 ,SUM(Saldo_ML) AS Saldo_ML
		 ,SUM(importe) AS Importe
		 ,'TC' AS sheet
     FROM ##TEMP_Cartera
	group by FECHA_CIERRE
		 ,ENTIDAD
		 ,codigo_cuenta